// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const PROCESS_ENV = typeof process !== "undefined" ? process.env : undefined;
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || PROCESS_ENV?.SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || PROCESS_ENV?.SUPABASE_PUBLISHABLE_KEY;

export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

export const supabaseConfigErrorMessage = (() => {
  const missing = [
    ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
    ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
  ];
  return missing.length > 0
    ? `Missing Supabase environment variable(s): ${missing.join(", ")}. Configure them in your hosting provider.`
    : null;
})();

function createSupabaseClient() {
  if (!isSupabaseConfigured) {
    console.error(`[Supabase] ${supabaseConfigErrorMessage}`);
    throw new Error(supabaseConfigErrorMessage ?? "Missing Supabase environment variables.");
  }

  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
